{% set version = "0.2-15" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-skmeans
  version: {{ version|replace("-", "_") }}

source:
  fn: skmeans_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/skmeans_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/skmeans/skmeans_{{ version }}.tar.gz
  sha256: 81559336e21bbde02f58dff3f06aa70c30f7caa500e5c58b9874b5306700089b

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-clue >=0.3_39
    - r-cluster
    - r-slam >=0.1_31

  run:
    - r-base
    - r-clue >=0.3_39
    - r-cluster
    - r-slam >=0.1_31

test:
  commands:
    - $R -e "library('skmeans')"  # [not win]
    - "\"%R%\" -e \"library('skmeans')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=skmeans
  license: GPL-2
  summary: Algorithms to compute spherical k-means partitions. Features several methods, including a genetic and a fixed-point algorithm and an interface to the CLUTO vcluster program.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
