# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qg2H5X+c19e6PXTNiwv8OM2/XnD3GU3Xdn3VLTIpSb09+b7wIVOYYsqg5ts7pb0Y8hJsgVUHzCL1Em3+N74hVMgng99m1zWvbguyVzTurVkDyh8hE7PyOQDVTR4alLPfCjF8TOdqz2QXYsSbb34d/f17pUQWaxNnGqGnexV0OlCS2b7WT+QhoSdMy2NA/cCELoPIiK/REPEhqrdKRRTYE6T7k/qJHFvySmdtUQuNQGuV/bj/pSWU+aBBYXmNtYMglEdn/BXbqig8XSA5vcS59C6obt4vS3oizx0qT4Zy+W7JqPcDEBFKZ3dLLGdOu4zL4unmwXdCgaRDNsgkWb9PeOSjpbVNoBRcs+8vGoyryI11RghSmYNdrsuYdAzZwsF3xVtQJRFfHg4Ei5CSPlL8LUOYjIwr9Yr/gd2O0mdFOf4XmSSvASJh27voAVmwcg1pXd3PDfPFhZRkUbCiusNvC7vhmPO6cLngul1wHoGE77ABC3DMylFNHXXICRZEjJnTXQux/rrhLvvtxOcU79uZg1Od16f9sPhqGNZYNL0zwvAn6/cMFXW6CfoGWp6OU5EWU93fnalxKpxZxwbQHwmZsJRVCjUaIlAnQck0DBS+7MuzjFpO5ut3ze45bwYi+MaFVCzXj/vDCSJaZKAq+voshuHYflxI/u+6UEDk7Lvx0mc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
