appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: V8yyGdl8+YOlSU+adScfMTvSNtw+mVMYx8owPLWFv2e8mnvJhhm1b4gSb2HdyZnrN73Tpa2XaRgrICVUjYFerf9UMLMTZ51qDU3Em6+1zPUQ3ftuFlaDseAOsducuqpitZbSmUESMqwnp4K/Y3AVrtNV7lGhYs3e/ZQd90k5hijojqmfdrMkKvWtRgDyXOfJN+Bj6u8UzsTadXQ7WAveZujsjWyRvAh7XnNS7IZLiUfhdUUZn5bOZlgI6cvTGeNjdisH20JOfkpHhx6u6Ok4WfTssAvXuo/NwYpbSQ1BiSG83oIekJOk6+2XLVPp7YoLUG6vnq/ZiP0GPdMJOAr7QUBKXBh49O3R2aJokPZCeESXqUjSyqnG6mn2ObNwTyiIiDbuyxGCRWxVzzW+U9B5GhOqvOmne/MDXPTTSA7FJ8pVJPKWDunZK0hRCe+l/+0sw9b2LHw54q8u/FeEdritfUJXtYMtrIzGPYtYhotG81fI8L8qv8VMzZSBAgZDyb1Swpp3TRZiSL+E++HmcIxUP1JqQloBQ3eth3ndEeRWT6vr/ts52hYUF0jNV+f/ZZjnAr4Fi9jRw4d8W2o0gVp0Xvxswo0zmsTiHIScVOi86edhazD6eFz0Ld9n/dbmybYTxxgGLSApEA+mjMBB1n0YG6OuqmQFebmy6ActQnFa/XA=}
