travis:
  secure:
    BINSTAR_TOKEN: qg2H5X+c19e6PXTNiwv8OM2/XnD3GU3Xdn3VLTIpSb09+b7wIVOYYsqg5ts7pb0Y8hJsgVUHzCL1Em3+N74hVMgng99m1zWvbguyVzTurVkDyh8hE7PyOQDVTR4alLPfCjF8TOdqz2QXYsSbb34d/f17pUQWaxNnGqGnexV0OlCS2b7WT+QhoSdMy2NA/cCELoPIiK/REPEhqrdKRRTYE6T7k/qJHFvySmdtUQuNQGuV/bj/pSWU+aBBYXmNtYMglEdn/BXbqig8XSA5vcS59C6obt4vS3oizx0qT4Zy+W7JqPcDEBFKZ3dLLGdOu4zL4unmwXdCgaRDNsgkWb9PeOSjpbVNoBRcs+8vGoyryI11RghSmYNdrsuYdAzZwsF3xVtQJRFfHg4Ei5CSPlL8LUOYjIwr9Yr/gd2O0mdFOf4XmSSvASJh27voAVmwcg1pXd3PDfPFhZRkUbCiusNvC7vhmPO6cLngul1wHoGE77ABC3DMylFNHXXICRZEjJnTXQux/rrhLvvtxOcU79uZg1Od16f9sPhqGNZYNL0zwvAn6/cMFXW6CfoGWp6OU5EWU93fnalxKpxZxwbQHwmZsJRVCjUaIlAnQck0DBS+7MuzjFpO5ut3ze45bwYi+MaFVCzXj/vDCSJaZKAq+voshuHYflxI/u+6UEDk7Lvx0mc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
