travis:
  secure:
    BINSTAR_TOKEN: bUxstFKKEPK86VoiXMPHkL3OmJ+fR5tRknks0Kskx6V41Bad9NDAMLIaUEIu0BFph9ITmqSm9Sprr7oVXKgIhyu8QLVJPGd74bmtNTlXYN76onQc95pOAk/v8ZWrCc3Yo4MpiuxtNr5cc/P2B4+Hxf4+xQEYILHYAW5cOeOQOEG3X+fYOwW5ijSvs7r4vy2paePNqaRmQRFEL8ZpUQYE01lZcqza/MaokvfWwZGZfRY8BZobZ6BoLzQKbkmu/MIfF/CVm5QIjWB7HGCv15MRmrE5HG2SwgC1Aah4y22eU84M80Wc3vTq1yR1YFzg5reG0PE6dLsiiLa7NLqZmFpRYi6eHDd21XUVKEMnggn3kSiYW5hkbT7TKaD4Shu4g+rq2UFlDev1jXe3YG4/mol4scUIxoXprR0QQnuhobKp2aNgG4R5a+arXwTlySJ8bauujJWWuegVqzgo4vKES6lsLuYhwqXGAFM0ZVzh9U9T2omzA9RSerJm5M6BIlUVjKOHwavMSZ9qL4gnuLi8CoSuC8GtWqG2zmmFP9hXfP2yuBDjG/Mtntl7bf/hZOt/ZR9rS1U9+NrnjzpzrNJVeKpeswHBHfd0VMSYWW7eUK9w6JJpVDNw/uuNm5M/S6M0+B/ZukgktImNiXG4SrjipexeFdAYUnkCnVZTpnl/6FE69mY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
